export const CHANGE_LOADING_STATUS = "CHANGE_LOADING_STATUS";
export const CHANGE_MESSAGE_STATUS = "CHANGE_MESSAGE_STATUS";
export const SUCCESS_MESSAGE = "SUCCESS_MESSAGE";
export const FAILURE_MESSAGE = "FAILURE_MESSAGE";
